WIP
fmipython/PythonCourse2022 pull request #11
Opened 2022-10-15 21:16 UTC by luchev

2022-10-17 17:38 UTC, lyubolp requested changes

2022-10-17 17:38 UTC, lyubolp commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "# Not a Number (полезно като дъно на стел)\n",
typo in `стел`

2022-10-17 17:38 UTC, lyubolp commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "# Конвертиране на 1 списък до друг (map)\n",
Това сме го покрили в предната лекция (ФП)

2022-10-17 17:38 UTC, lyubolp commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "`queue` е tread-safe имплементация на опашка (FIFO). Може да я създадем с ограничен размер `Queue(maxsize=42)` - ако се напълни и се пробваме да добавим нов елемент ще се блокира нишката. `m
typo in `tread-safe`

2022-10-17 17:38 UTC, lyubolp commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "Писането на регулярни изрази обикновено е трудоемка задача, за това препоръчваме инструменти като [regexr](https://regexr.com/), които изпълняват regex в реално време и имат обяснение защо д
typo in `стринге`

2022-10-17 17:38 UTC, lyubolp commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "TODO zadacha s queue vs stack - dfs / bfs\n",
Да не ги забравим

2022-10-17 19:43 UTC, luchev commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "# Конвертиране на 1 списък до друг (map)\n",
Removed

2022-10-17 19:43 UTC, luchev commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "# Not a Number (полезно като дъно на стел)\n",
Fixed

2022-10-17 19:44 UTC, luchev commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "`queue` е tread-safe имплементация на опашка (FIFO). Може да я създадем с ограничен размер `Queue(maxsize=42)` - ако се напълни и се пробваме да добавим нов елемент ще се блокира нишката. `m
Fixed

2022-10-17 19:44 UTC, luchev commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "Писането на регулярни изрази обикновено е трудоемка задача, за това препоръчваме инструменти като [regexr](https://regexr.com/), които изпълняват regex в реално време и имат обяснение защо д
Fixed

2022-10-23 17:49 UTC, luchev commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "TODO zadacha s queue vs stack - dfs / bfs\n",
fixed

2022-10-23 17:52 UTC, lyubolp approved these changes

2022-10-27 08:20 UTC, yalishanda42 requested changes

2022-10-27 08:20 UTC, yalishanda42 commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "![https://i.imgur.com/dVcLsFl.png](https://i.imgur.com/dVcLsFl.png)"
Продуктово позициониране

2022-10-27 08:20 UTC, yalishanda42 commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "print('Може да направим всички символи голем:', s.upper())\n",
typo: голем -> големи

2022-10-27 08:20 UTC, yalishanda42 commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +            "Закръгляне на горе 2.2 -> 3\n",
нагоре* и надолу*

2022-10-27 08:20 UTC, yalishanda42 commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "При инициализиране трябва да окажем типа на елемтнтите в списъка.\n",
typo: елементите*

2022-10-27 08:20 UTC, yalishanda42 commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "        try:\n",
Сигурен ли си, че този try - while True - except StopIteration няма да може да стане с `for`?

2022-10-27 08:20 UTC, yalishanda42 commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "# Защото по някога имплементирането им просто не е тривиално ...\n",
понякога*

2022-10-27 08:20 UTC, yalishanda42 commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "    def less_msb(self, x, y) -> bool:\n",
Следващата тема чак е typing, може да махнем `-> bool` тука че да няма surprise pikachu faces

2022-10-27 15:22 UTC, luchev commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "![https://i.imgur.com/dVcLsFl.png](https://i.imgur.com/dVcLsFl.png)"
https://i.imgur.com/jWr67J8.png

2022-10-27 15:24 UTC, luchev commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "print('Може да направим всички символи голем:', s.upper())\n",
не ти ли харесва голем?! fixed

2022-10-27 15:26 UTC, luchev commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "        try:\n",
Това го копнах от документацията. Сигурно може с for, но това ми изглежда доста красиво?

2022-10-27 16:31 UTC, yalishanda42 commented on 05 - Data Structures and Oddities/05 - Data Structures and Oddities.ipynb
> +        "        try:\n",
ми на мене не ама нека влиза

2022-10-27 16:31 UTC, merged