04 more tasks
fmipython/PythonCourse2022 pull request #14
Opened 2022-10-27 19:30 UTC by lyubolp

Tasks for 04 - Functional programming

2022-10-27 20:40 UTC, yalishanda42 requested changes

2022-10-27 20:40 UTC, yalishanda42 commented on 04 - Functional Programming/tasks/tasks.md
> +- `Divide`, който умножава почленно елементите на двата списъка
тука предполагам трябва да пише "дели"

2022-10-27 20:40 UTC, yalishanda42 commented on 04 - Functional Programming/tasks/tasks.md
> +Този процес продължава до изчерпване на операциите/елементите.
А какво се връща накрая? Всички резултати от операциите или само финалния?

2022-10-27 20:40 UTC, yalishanda42 commented on 04 - Functional Programming/tasks/tasks.md
> +`[15, -17, 19, -17]`
честно казано не разбирам много как се получава резултата и също така ако има различен брой елементи какво е поведението :/

2022-10-30 14:05 UTC, lyubolp commented on 04 - Functional Programming/tasks/tasks.md
> +- `Divide`, който умножава почленно елементите на двата списъка
Fixed

2022-10-30 14:07 UTC, lyubolp commented on 04 - Functional Programming/tasks/tasks.md
> +Този процес продължава до изчерпване на операциите/елементите.
Връща се резултата от последната операция (наподобява поведението на `reduce`)

2022-10-30 14:19 UTC, lyubolp commented on 04 - Functional Programming/tasks/tasks.md
> +`[15, -17, 19, -17]`
Оставят се as-is. Допълних условието с обяснение

2022-10-30 18:56 UTC, yalishanda42 approved these changes

2022-11-01 17:33 UTC, merged