Added initial version of the projects guidelines
fmipython/PythonCourse2022 pull request #15
Opened 2022-11-01 17:34 UTC by lyubolp

Дефиниция на проектите и оценяването им. pls review

2022-11-01 17:46 UTC, yalishanda42 requested changes

2022-11-01 17:46 UTC, yalishanda42 commented on projects.md
> +- Добра идея е проекта да е качен в Git (Github, Gitlab, Bitbucket, т.н.)
Можем да ползваме Github Classroom за проектите пак

2022-11-01 17:46 UTC, yalishanda42 commented on projects.md
> +   - Може да използвате PyGame ило други
typo: *или

2022-11-01 17:46 UTC, yalishanda42 commented on projects.md
> +- **Git** - 5 точки
Какво ще рече да оценяваме `git`? Или просто 5 точки ако ползват version control? Няма смисъл imo, още повече ако решим да ползваме github classroom и за това

2022-11-01 17:46 UTC, yalishanda42 commented on projects.md
> +- **Git** - 5 точки
Може още 5 точки да идат за PEP-8 например

2022-11-01 18:07 UTC, lyubolp commented on projects.md
> +- **Git** - 5 точки
Дори и да ползваме Classroom (не знам колко съм съгласен с това де), добре е да имат добри commit-и, commit messages, т.н.

2022-11-01 18:08 UTC, lyubolp commented on projects.md
> +- Добра идея е проекта да е качен в Git (Github, Gitlab, Bitbucket, т.н.)
Не съм съглсасен, по-добре да си е отделно repo - но няма да споря много по тая тема :D

2022-11-01 18:10 UTC, yalishanda42 commented on projects.md
> +- Добра идея е проекта да е качен в Git (Github, Gitlab, Bitbucket, т.н.)
Ами то си е отделно репо, просто не е публично в техния гитхъб, а е private към организацията as far as i can remember (на Scala курса и проектите ни бяха в classroom-a, което го разбрах накрая и трябваше да пушвам всички къмити наново в другото репо :д)

2022-11-01 18:11 UTC, yalishanda42 commented on projects.md
> +- Добра идея е проекта да е качен в Git (Github, Gitlab, Bitbucket, т.н.)
Единствения минус, който се сещам на classroom-а в случая е, че няма да могат групови проекти да правят така. Но пък ние и без това не искаме групови проекти тази година поне

2022-11-01 18:19 UTC, yalishanda42 commented on projects.md
> +- **Git** - 5 точки
Еми да, въпреки че не е пряко свързано с Python съм съгласен. Може PEP-8 пък да влезе към критерия за Pythonic code.

2022-11-01 18:38 UTC, luchev commented on projects.md
> +- Добра идея е да имате тестове
Тестовете са задължителни (носят точки). Следователно да променим "Добра идея" на "Трябва".
"Добра идея" = Яко е ама е бонус.

2022-11-01 18:38 UTC, luchev commented on projects.md
> +- Добра идея е проекта да е качен в Git (Github, Gitlab, Bitbucket, т.н.)
По-добре да са си в тяхно репо, така може да си го ползват за CV/portfolio.

2022-11-01 18:38 UTC, luchev commented on projects.md
> +- Очакваме демонстрация на проекта
Повече детайли. Пример:
На изпита ще трябва за 2-4 минути да демонстрирате проекта. След това 2-4 минути да разгледаме кода. 2-4 минути за въпроси.

2022-11-01 18:38 UTC, luchev commented on projects.md
> +- Проектите ви трябва да могат да бъдат пуснати на друга машина - кратък INSTALL.md файл с инструкции би ни свършил работа
Добра идея е репото да има README https://github.com/othneildrew/Best-README-Template.
INSTALL.md не виждам много често. По-добре в readme-то да има секция
We like this :)

2022-11-01 18:38 UTC, luchev commented on projects.md
> +
```suggestion
## Примерни идеи
```

2022-11-01 18:38 UTC, luchev commented on projects.md
> +   - Четене/писането от файл е силно препоръчителна функционалност
??? why

Примери:
* Multithreaded реализация на сложен алгоритъм
* Конзолна игра (pacman)
* Всякакво приложение което използва pipes/subprocesses/sockets
* CLI който работи с някакъв API (примерно github)

2022-11-01 18:38 UTC, luchev commented on projects.md
> +   - Четене/писането от файл е силно препоръчителна функционалност
Работата с GUI е достатъчно сложна, за четене/писане на файл

2022-11-01 18:38 UTC, luchev commented on projects.md
> +   - Ако имате идея да напишете библиотека за нещо което го няма - очакваме много добро пакетиране, разделение на модули, добри абстракции и error handling
tests

2022-11-01 18:38 UTC, luchev commented on projects.md
> +​	**Нямаме краен срок за избирането на тема**, но е препоръчително преди Коледната ваканция да имате тема по която да работите (не сте във ФМИ ако не пишете код по Коледа). **Крайният срок за проекти
sus

2022-11-01 18:38 UTC, luchev commented on projects.md
> +  - SOLID, DRY, YAGNI, добро именуване, кратки функции и т.н. -  5 точки
Мани ги тея buzzwords (╯°□°)╯︵ ┻━┻. Сложи нещо по-смислено като:
* linted code
* well structured README
* използване на билд скриптове/система (make/just)
* requirements.txt

2022-11-01 18:38 UTC, luchev commented on projects.md
> +- **Git** - 5 точки
5 точки за гит са много като работят сами. Има смисъл ако са групови проекти - да има PRs, Code reviews, etc.

Може да сложим 2 бонус точки ако ползват CI/CD за тестове/билдване

2022-11-01 18:43 UTC, yalishanda42 commented on projects.md
> +  - SOLID, DRY, YAGNI, добро именуване, кратки функции и т.н. -  5 точки
доста съгласен за всички без билд скриптовете, те нека бъдат за бонус точки

2022-11-02 19:38 UTC, lyubolp commented on projects.md
> +- Проектите ви трябва да могат да бъдат пуснати на друга машина - кратък INSTALL.md файл с инструкции би ни свършил работа
Да, написах install.md-то като пример само

2022-11-02 19:45 UTC, lyubolp commented on projects.md
> +   - Четене/писането от файл е силно препоръчителна функционалност
1) Работата с файлове (и context managers) в Python си е специфична откъм синтаксис. 
2) Отваря възможността за доста интересни функционалности - към примера за console game - high score saving може да направиш чрез файлове, или пък работа с конфигурационни файлове в други видове проекти. 

Естествено, ако няма смисъл въобще в проекта, няма да трябва да има файлове.

2022-11-02 19:46 UTC, lyubolp commented on projects.md
> +   - Четене/писането от файл е силно препоръчителна функционалност
Сложна не знам, по-скоро repetitive - PySimpleGui прави нещата доста лесни за правене. Относно файлове, виж предишния коментар

2022-11-02 19:49 UTC, lyubolp commented on projects.md
> +  - SOLID, DRY, YAGNI, добро именуване, кратки функции и т.н. -  5 точки
Напълно валидно е да имаш linted code, който е кофти написан откъм дизайн.  PEP8 не проверява за добър дизайн. Може да са buzzwords, ама са валидни - те дефинират насоки за добър код/дизайн. 

За README-то съм съгласен, валидно е, както и requirements.txt.

Build scripts според мен е overkill, не сме CI/CD курс - deployment-а на Python код като цяло е тегав, и `make` не прави нещата много по-лесни

2022-11-02 19:51 UTC, lyubolp commented on projects.md
> +- **Git** - 5 точки
Очаквам да имат repo и да има смислени commit-и. Съгласен съм да е по-малко точки за git.

2022-11-02 19:53 UTC, luchev commented on projects.md
> +   - Четене/писането от файл е силно препоръчителна функционалност
> Естествено, ако няма смисъл въобще в проекта, няма да трябва да има файлове.
Съгласен. Коментирах защото на няколко места имаше "препоръчваме файлове", което ми изглеждаше като натякване да ползват файлове във всеки проект :D

2022-11-06 20:11 UTC, yalishanda42 commented on projects.md
> +  - SOLID, DRY, YAGNI, добро именуване, кратки функции и т.н. -  5 точки
Може вместо 5 за гит да дадем 2 за гит и 3 за requirements.txt, REDME, документация, т.н.

2022-11-06 20:22 UTC, yalishanda42 commented on projects.md
> +  - SOLID, DRY, YAGNI, добро именуване, кратки функции и т.н. -  5 точки
* Функционалност: 10т.
* Качество: 20т., от които:
    * pythonic: 4т.
    * PEP-8: 2т.
    * clean code: 9т., от които:
        * спазване на принципи и стил: 7т.
        * type hints: 2т.
    * модулите: 5т.
* Git: 2т.
* requirements + readme: 3т.
* тестове: 5т.

2022-11-08 18:31 UTC, lyubolp commented on projects.md
> +   - Може да използвате PyGame ило други
fixed

2022-11-08 20:15 UTC, lyubolp commented on projects.md
> +- Добра идея е да имате тестове
Fixed

2022-11-08 20:23 UTC, lyubolp commented on projects.md
> +  - SOLID, DRY, YAGNI, добро именуване, кратки функции и т.н. -  5 точки
fixed

2022-11-08 20:33 UTC, luchev approved these changes

2022-11-08 23:29 UTC, yalishanda42 approved these changes

2022-11-08 23:29 UTC, merged