Add instructions for assignments
fmipython/PythonCourse2022 pull request #18
Opened 2022-11-09 13:29 UTC by luchev

2022-11-09 13:57 UTC, yalishanda42 commented
Добре е да reference-нем новия файл в README-то

2022-11-09 13:57 UTC, yalishanda42 requested changes

2022-11-09 13:57 UTC, yalishanda42 commented on assignments.md
> +4. За да предадете домашното си трябва да git commit-нете промените си и да ги push-нете в main branch-а.
```suggestion
4. За да предадете домашното си трябва да git commit-вате промените си и да ги push-вате в main branch-а.
```
Бих го променил на това, за да стане ясно, че е continuous процес, а не всичко наведнъж в един къмит

2022-11-09 22:36 UTC, luchev commented
> Добре е да reference-нем новия файл в README-то

Done

2022-11-10 22:10 UTC, yalishanda42 requested changes

2022-11-10 22:10 UTC, yalishanda42 commented on README.md
> +Инструкции за заданията може да намерите [тук](https://github.com/fmipython/PythonCourse2022/blob/main/README.md)
```suggestion
Инструкции за заданията може да намерите [тук](https://github.com/fmipython/PythonCourse2022/blob/main/assignments.md)
```
i guess that's what u meant

2022-11-11 06:40 UTC, lyubolp requested changes

2022-11-11 06:40 UTC, lyubolp commented on assignments.md
> +2. Трябва да свържете GitHub профила си със GitHub Classroom като изберете факултетния си номер ор списъка с участници
typo: 'ор' => 'от'

2022-11-11 06:40 UTC, lyubolp commented on assignments.md
> +5. След като приключите заданието трябва да го архивирате и да го качите като .zip в Moodle
Предполагам няма направено задание в Мудъл?

2022-11-11 06:40 UTC, lyubolp commented on assignments.md
> +1. На датата на заданието ще получите линк с покана за GitHub Classroom задание
Бих го reword-нал на "На датата на започването на заданието"

2022-11-11 09:41 UTC, luchev commented on assignments.md
> +5. След като приключите заданието трябва да го архивирате и да го качите като .zip в Moodle
Не, този документ е за всички задания, за това няма специфични линкове. Може да направим заданието в мудъл и там да сложим линка

2022-11-11 09:47 UTC, yalishanda42 approved these changes

2022-11-12 07:01 UTC, lyubolp approved these changes

2022-11-12 08:31 UTC, merged