[03] OOP
fmipython/PythonCourse2022 pull request #4
Opened 2022-09-09 12:24 UTC by allexks

2022-09-09 12:26 UTC, allexks commented
note to self: rerun outputs after resolving comments

2022-09-09 13:58 UTC, luchev commented on 03 - OOP/03 - OOP.ipynb
> +    "    x = 69\n",
Nice

2022-09-09 13:58 UTC, luchev commented on 03 - OOP/03 - OOP.ipynb
> +    "В примерът по-горе използвахме доста непознати dunder-и: `__repr__`, `__dict__`, `__class__`, `__name__`. За тях, както и други, ще разясним в следващат секция."
следващат -> следващата

2022-09-09 13:58 UTC, luchev commented on 03 - OOP/03 - OOP.ipynb
> +    "***TODO: COMPLETE LIST***"
Remaining TODO

2022-09-09 13:58 UTC, luchev commented on 03 - OOP/03 - OOP.ipynb
> +    "print(\"👏\".join(i for i in it))  # __iter__ is also called by comprehensions, more info on list/generator/dict comprehensions in another lecture\n"
Very long lines are cut off by Github it seems

2022-09-09 14:16 UTC, lyubolp requested changes

2022-09-09 14:16 UTC, lyubolp commented on 03 - OOP/03 - OOP.ipynb
> +    "| `|`        | `__or__`, `__ror__`             |\n",
Rendering-а се е прецакал тука

2022-09-09 14:16 UTC, lyubolp commented on 03 - OOP/03 - OOP.ipynb
> +    "| `|=`       | `__ior__`                       |\n",
Тук също
![Screenshot_20220909_170750](https://user-images.githubusercontent.com/17728894/189369207-e60a0594-224c-4ef6-b1da-38223081e1c0.png)

2022-09-09 14:16 UTC, lyubolp commented on 03 - OOP/03 - OOP.ipynb
> +    "### Контекстни мениджъри и `with`"
Не е ли малко рано за това ? 
Предлагам да го оставим за лекцията за работа с файлове. Там може да покажем и как се имплементира в клас

2022-09-09 20:06 UTC, allexks commented on 03 - OOP/03 - OOP.ipynb
> +    "    x = 69\n",
> Nice

Nice

2022-09-09 20:08 UTC, allexks commented on 03 - OOP/03 - OOP.ipynb
> +    "### Контекстни мениджъри и `with`"
Ми добре, няма проблеми

Позволявам ти да си го вземеш директно, ако ти харесва така обяснено :D

2022-09-09 20:52 UTC, allexks commented on 03 - OOP/03 - OOP.ipynb
> +    "| `|=`       | `__ior__`                       |\n",
FYI: Разбрах какъв му е проблема - `|` трябва да се escape-не с `\|` понеже си мисли, че свършва колоната

2022-09-10 13:48 UTC, lyubolp approved these changes

2022-09-10 22:19 UTC, merged