08 files
fmipython/PythonCourse2022 pull request #6
Opened 2022-09-13 19:59 UTC by lyubolp

2022-09-13 20:08 UTC, lyubolp commented
Трябва да добавя type hinting

2022-09-14 18:37 UTC, yalishanda42 requested changes
Доста изчерпателно написано и лесно за проследяване и четене, gj

2022-09-14 18:37 UTC, yalishanda42 commented on 08 - Files/08 - Files.ipynb
> +        "Преместването на файл става чрез \"преименуването му\" (или всъщност, преименуването на файл е преместването му като файл с друго име 🤔) - това в Python става с помощта на функцията `os.rena
Малко е тавтология два пъти едно след друго да пише `os.rename` - може да замениш второто с "Тя" (функцията).

2022-09-14 18:37 UTC, yalishanda42 commented on 08 - Files/08 - Files.ipynb
> +        "Изтриването на файл се случва чрез метода `os.remove`. `os.remove` приема един аргумент - пътят към файла, който ще бъде изтрит."
И тук

2022-09-14 18:37 UTC, yalishanda42 commented on 08 - Files/08 - Files.ipynb
> +        "В Python създаването на директория става чрез метода `os.mkdir`. `os.mkdir` приема пътя към директорията, която да бъде създадена. "
И тук

2022-09-14 18:37 UTC, yalishanda42 commented on 08 - Files/08 - Files.ipynb
> +        "Тук получаваме грешка - `os.mkdir` не може да създаде несъществуващите директории над последната. За целта трябва да използваме метода `os.makedirs`. `os.makedirs` приема отново като аргумен
И тук

2022-09-14 18:37 UTC, yalishanda42 commented on 08 - Files/08 - Files.ipynb
> +        "Изтриването на директория става чрез `os.rmdir`. `os.rmdir` приема пътя към директорията, която трябва да бъде изтрита. "
И тук

2022-09-14 18:37 UTC, yalishanda42 commented on 08 - Files/08 - Files.ipynb
> +        "При работа с текстови файлове, отместването е само спрямо началото на файла. Можем единствено да преместим курсора до края на файла с `seek(0, 2)`"
Тука е хубаво да се каже различните стойности за `whence` какво значат, понеже са на пръв поглед някакви магически числа, които нищо не ни говорят. Също така съществуват и константите `os.SEEK_SET`, `os.SEEK_CUR` и `os.SEEK_END`

2022-09-14 18:37 UTC, yalishanda42 commented on 08 - Files/08 - Files.ipynb
> +        "    Person('Ivan', 'Luchev', '28-04-1998', 24, 'Student')\n",
i didn't sign gdpr lol

jk

2022-09-14 19:38 UTC, yalishanda42 approved these changes

2022-09-16 05:56 UTC, luchev approved these changes

2022-09-16 05:56 UTC, merged